### ISSUE TITLE
Undocumented detail in the setup of settings.yml

### ISSUE THREAD

**Issue by europ** [ManageIQ/miq_bot#407]
`NoMethodError: undefined method 'each' for nil:NilClass`

at

https://github.com/ManageIQ/miq_bot/blob/ca62968398d181fa6155264cda053ec06c56159d/app/workers/commit_monitor_handlers/commit_range/path_based_labeler.rb#L21

```
2018-02-21T07:42:11.405Z 24598 TID-gnaf0hvnk WARN: NoMethodError: undefined method `each' for nil:NilClass
2018-02-21T07:42:11.405Z 24598 TID-gnaf0hvnk WARN: /root/miq_bot/app/workers/commit_monitor_handlers/commit_range/path_based_labeler.rb:21:in `process_branch'
/root/miq_bot/app/workers/commit_monitor_handlers/commit_range/path_based_labeler.rb:14:in `perform'
/root/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/sidekiq-4.1.4/lib/sidekiq/processor.rb:152:in `execute_job'
...
```

due to uninitialized variable

https://github.com/ManageIQ/miq_bot/blob/ca62968398d181fa6155264cda053ec06c56159d/config/settings.yml#L28

Example how to solve:

```yaml
...

# Worker settings
diff_content_checker:
  offenses: {}
merge_target_titler:
  included_repos: []
path_based_labeler:
  rules:
    organization/repository: []
travis_build_killer:
  included_repos: []
```

**Comment by Fryguy** [comment]
strange...how is this working in production?  We definitely don't have rules for every repo, and according to https://github.com/ManageIQ/miq_bot/blob/8bbabd9c3dc8c7dd6755d3b7128b3ad3426713d4/app/workers/commit_monitor_handlers/commit_range/path_based_labeler.rb#L31 a missing repo will return nil.

**Comment by juliancheal** [comment]
> a missing repo will return nil.

Yeah but returning nil, means https://github.com/ManageIQ/miq_bot/blob/master/app/workers/commit_monitor_handlers/commit_range/path_based_labeler.rb#L21 blows up.

**Comment by Fryguy** [comment]
Right, so I can't understand how's it's working in production presently.  It should be blowing up constantly.

**Comment by europ** [comment]
What are the rules in production?
```yml
path_based_labeler:
  rules:
```
I always faced this `NoMethodError` until I added some empty fake `org/repo` into rules to make them non-empty.

**Comment by Fryguy** [comment]
yeah, it turns out it's a coincidence that it's working in production...the settings are:

```yaml
path_based_labeler:
  included_repos:
  - ManageIQ/manageiq
  - ManageIQ/manageiq-ui-classic
  rules:
    ManageIQ/manageiq:
    - ...
    ManageIQ/manageiq-ui-classic:
    - ...
```

So, we happen to set the included_repos as well as the rules which ensures only those valid repos are even called.
