### ISSUE TITLE
PathBasedLabeler needs a "*" target

### ISSUE THREAD

**Issue by Fryguy** [ManageIQ/miq_bot#431]
The PathBasedLabeler requires configuration of each repo and their rules individually and there is no way to make a simple global rule.

current:

```yaml
path_based_labeler:
  included_repos:
  - ManageIQ/manageiq
  - ManageIQ/manageiq-ui-classic
  rules:
    ManageIQ/manageiq:
    - *ansible_tower_rule
    - *dependencies_rule
    - *sql_migration_rule
    ManageIQ/manageiq-ui-classic:
    - *graphics_rule
    - *dependencies_rule
```

requested:

```
path_based_labeler:
  included_repos: *core_repos
  rules:
    "*":
    - *dependencies_rule
    - *sql_migration_rule
    ManageIQ/manageiq:
    - *ansible_tower_rule
    ManageIQ/manageiq-ui-classic:
    - *graphics_rule
