### ISSUE TITLE
Cross Repo Testing

### ISSUE THREAD

**Issue by Fryguy** [ManageIQ/miq_bot#446]
The bot should accept a command on a PR to allow for cross-repo testing.

Expected message format:

`@miq-bot run-tests [<repos-to-test>] [including <gem-repos>]`

where:
- a repo is of the form `[org/]repo[@ref|#pr]`
- `repos-to-test` is a comma separated list of repos
- `gem-repos` is a set of gem repos

---

When the bot sees this command it will create a commit/PR against the cross-repo app [1].  The commit contents will modify the .travis.yml and set the env vars to match what was requested in the command

[1] presently in https://github.com/Fryguy/manageiq-cross_repo, but expected to be moved soon (and possibly split into separate library and execution repos).

---

Examples

- In ManageIQ/manageiq PR `#1234`:

  `@miq-bot run-tests manageiq-ui-classic`

  will create a commit with the .travis.yml changes:

  ```yaml
  env:
    global:
    - REPOS=ManageIQ/manageiq#1234,Fryguy/more_core_extensions@feature,Fryguy/linux_admin@feature
    matrix:
    - TEST_REPO=manageiq-ui-classic
  ```

- In ManageIQ/manageiq PR `#1234`:

  `@miq-bot run-tests manageiq-ui-classic,manageiq-api including Fryguy/more_core_extensions@feature,Fryguy/linux_admin@feature`

  will create a commit with the .travis.yml changes:

  ```yaml
  env:
    global:
    - REPOS=ManageIQ/manageiq#1234,Fryguy/more_core_extensions@feature,Fryguy/linux_admin@feature
    matrix:
    - TEST_REPO=manageiq-ui-classic
    - TEST_REPO=manageiq-api
  ```

- In ManageIQ/manageiq-ui-classic PR `#1234`:

  `@miq-bot run-tests manageiq`

  will create a commit with the .travis.yml changes:

  ```yaml
  env:
    global:
    - REPOS=ManageIQ/manageiq-ui-classic#1234
    matrix:
    - TEST_REPO=ManageIQ/manageiq
  ```

---

Other:
- The command should only works on PRs, and fail on issues
- The command should only be executable by the PR author or any member of the ManageIQ org.
